### ISSUE TITLE
#Feature - [2.0] macOS support?

### ISSUE THREAD

**Issue by MasterCruelty** [TheMergers/eMerger#80]
The purpouse of this issue is to check if macOS can be supported by eMerger without too much diffucilty or time spent.
The main problem is the interpreter because macOS uses <code>#!bin/sh</code> instead of <code>#!/bin/bash</code>

**Comment by MasterCruelty** [comment]
@archetipico I just discovered that <code>zsh</code> is compatible with <code>bash</code> thanks to @NespoliBT

**Comment by archetipico** [comment]
I know very little about how macOS works. Though the problem is not zsh, the problem is that IF I'm not wrong, macOS isn't updated to the last Bash version since it's under GPLv3.
Moreover, I never used zsh but I think the file should start with a proper zsh call and not with a `#!/bin/bash` call.

**Comment by MasterCruelty** [comment]
> I know very little about how macOS works. Though the problem is not zsh, the problem is that IF I'm not wrong, macOS isn't updated to the last Bash version since it's under GPLv3.
> Moreover, I never used zsh but I think the file should start with a proper zsh call and not with a `#!/bin/bash` call.

What if macOS reads <code>#!/bin/bash</code> and it converts automatically in zsh because of the compatibility? Considering what @NespoliBT said to me

**Comment by NespoliBT** [comment]
If you want to have MacOS campatibility i would raccomend having a cross platform script (for example a py executable) that redirects to the correct update script.

**Comment by archetipico** [comment]
Though this means we have to create a separate macOS version, since every file is in bash.

**Comment by MasterCruelty** [comment]
> If you want to have MacOS campatibility i would raccomend having a cross platform script (for example a py executable) that redirects to the correct update script.

I agree with @archetipico about this possibility

**Comment by MasterCruelty** [comment]
This will be solved by #109 and #110

**Comment by archetipico** [comment]
#110

**Comment by MasterCruelty** [comment]
> If you want to have MacOS campatibility i would raccomend having a cross platform script (for example a py executable) that redirects to the correct update script.

Finally we are approaching the idea of a py executable like we thought here years ago 🚀

**Comment by NespoliBT** [comment]
I can't believe it

**Comment by MasterCruelty** [comment]
> I can't believe it

Look at those new issues 😎 
A new branch is online...
